apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    field.cattle.io/creatorId: user-tomcat
  name: tomcat-liao-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
      - env:
        - name: INNO_DE_CONFIG_PATH
          value: /innode/app/config	  
        name: tomcat-liao-deployment
        image: 192.168.3.207:5000/fft/tomcat:v2.7
        ports:
        - containerPort: 8080
          name: 8080tcp10382
          protocol: TCP
        - containerPort: 8000		
          name: 8000tcp10383
          protocol: TCP
        volumeMounts:
        - mountPath: /usr/local/tomcat/webapps
          name: vol1-tomcat-data
          subPath: tomcat-webapps	
        - mountPath: /innode/app
          name: vol1-tomcat-data
          subPath: tomcat-app
        - mountPath: /innode/docs/upload
          name: vol1-tomcat-data
          subPath: tomcat-upload			  
      volumes:
      - name: vol1-tomcat-data
        persistentVolumeClaim:
          claimName: pipeline-tomcat		  
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
spec:
  selector:
    app: tomcat
  type: NodePort
  ports:
  - name: 8080tcp10381
    nodePort: 10382
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: 8000tcp10382
    nodePort: 10383
    port: 8000
    protocol: TCP
    targetPort: 8000